Add zettcache device support, DWARF call frame, and more perf stats collection
delphix/zfs pull request #410
Opened 2021-08-19 20:04 UTC by tonynguien

### Motivation and Context

DOSE-564 ZTS - Enable DWARF call frame for perf-record
DOSE-559 ZTS - Add network throughput and arcstat to data collected in tests
DOSE-573 ZTS - Add zettacache support

### Description

### How Has This Been Tested?

Ran ZFS performance test suite and verify dstat, arcstat, and perf files are generated. And `zfs_object_agent` runs with specified zettacache device.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2021-08-19 20:42 UTC, nupur-agrawal-delphix commented on scripts/zfs-tests.sh
> +		dev=$(basename "$ZETTA_CACHE_DEV")
Here, we are assuming that we will always have just 1 zetta cache device. What if we have multiple?

2021-08-19 20:47 UTC, jwk404 requested changes

2021-08-19 20:47 UTC, jwk404 commented on tests/zfs-tests/tests/perf/regression/random_reads.ksh
> +if [ -n "$ZETTA_CACHE_DEV" ]; then
What would you think about making this a function in perf.shlib?

2021-08-19 20:47 UTC, jwk404 commented on scripts/zfs-tests.sh
> +	if [ -n "$ZETTA_CACHE_DEV" ]; then
Can we add a line like the others at 699 that prints the value of this variable when the run starts?

2021-08-19 21:51 UTC, tonynguien commented on scripts/zfs-tests.sh
> +		dev=$(basename "$ZETTA_CACHE_DEV")
Zettacache code supports only a single device at the moment. IMO, we can update this logic when we have multiple devices support.

2021-08-19 21:51 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/random_reads.ksh
> +if [ -n "$ZETTA_CACHE_DEV" ]; then
Good idea! I'll do that.

2021-08-19 21:59 UTC, nupur-agrawal-delphix commented on scripts/zfs-tests.sh
> +		dev=$(basename "$ZETTA_CACHE_DEV")
Ah I didn't know that. Thanks !

2021-08-20 19:21 UTC, tonynguien commented on scripts/zfs-tests.sh
> +	if [ -n "$ZETTA_CACHE_DEV" ]; then
will do.

2021-08-20 20:14 UTC, jwk404 approved these changes

2021-08-24 01:29 UTC, merged