Adding performance file deletion test
delphix/zfs pull request #450
Opened 2021-09-15 22:54 UTC by tonynguien

### Motivation and Context

File deletion on object storage can take a long time. Adding a test so we can track file deletion.

### Description

Adding a new file deletion test. A single 2TB file is randomly written to using the specified per test duration before removing operation.

### How Has This Been Tested?

I'm still going through various testing with and without Zettacache device and comparing EBS-based pools.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2021-09-15 23:17 UTC, jwk404 requested changes

2021-09-15 23:17 UTC, jwk404 commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +export PERF_IOSIZES=${PERF_IOSIZES:-'8k'}
Some of these are already set in perflib.shlib from a recent change. Where they're identical, we can omit them here.

2021-09-15 23:17 UTC, jwk404 commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +fi
I think you can delete this, as it's duplicated below.

2021-09-15 23:17 UTC, jwk404 commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +	    "dstat -at --nocolor 1" "dstat"
dstat can produce csv output. Should we do that here for easier parsing later?
(I'm assuming the csv goes to stdout here, but not 100% sure about that)

2021-09-16 15:51 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +fi
I deleted the below section as we want to collect data during the random writing and the deletion.

2021-09-16 15:52 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +export PERF_IOSIZES=${PERF_IOSIZES:-'8k'}
We don't yet have that branch in the object storage branch.

2021-09-16 16:10 UTC, jwk404 approved these changes

2021-09-16 16:15 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +	    "dstat -at --nocolor 1" "dstat"
Yeah, I think we definitely want use csv when we're ready to working on parsing. Until then, I think it's nice to look at content for dstat same as other perf stat files.

2021-09-20 14:37 UTC, grwilson commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +log_note "Removing file"
Prior to starting the remove, you may need to wait for the I/Os to complete. I think `zpool sync <poolname>` will do that for you.

2021-09-20 15:36 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +log_note "Removing file"
After chatting with George, we'll go with:
1) async write by default (it's currently defaulting to sync)
2) zpool sync prior to rm
This way we can speed up the writes.

2021-09-20 16:57 UTC, tonynguien commented on tests/zfs-tests/tests/perf/regression/file_deletion.ksh
> +log_note "Removing file"
Using async, the the 5GB writes now takes ~2 minutes compared to >10 minutes with prior sync.

2021-09-20 17:00 UTC, grwilson approved these changes

2021-09-20 18:05 UTC, merged